<a href="https://colab.research.google.com/github/wwh0scare/wwh0scare.github.io/blob/main/preprocessing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_excel('dataset.xlsx')

In [4]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x)

[[Timestamp('2018-01-01 00:00:00') 'Monday' 281 'STNK' 'Sepeda Motor']
 [Timestamp('2018-01-01 00:00:00') 'Monday' 291 'SIM C' 'Sepeda Motor']
 [Timestamp('2018-01-01 00:00:00') 'Monday' 291 'SIM C' 'Sepeda Motor']
 ...
 [Timestamp('2023-12-26 00:00:00') 'Tuesday' 286 'STNK' 'Sepeda Motor']
 [Timestamp('2023-12-27 00:00:00') 'Wednesday' 291 'STNK' 'Sepeda Motor']
 [Timestamp('2023-12-31 00:00:00') 'Sunday' 287 'SIM A'
  'Mobil Penumpang Pribadi']]


In [6]:
print(y)

['Sedang' 'Ringan' 'Ringan' ... 'Ringan' 'Ringan' 'Ringan']


In [8]:
x = np.array([[np.nan, 'Monday', 10],
              [7, 'Tuesday', np.nan],
              [5, 'Wednesday', 15]])

In [9]:
numerical_data = x[:, [0, 2]].astype(float)
categorical_data = x[:, 1]

In [10]:
imputer_numeric = SimpleImputer(missing_values=np.nan, strategy='mean')
numerical_data = imputer_numeric.fit_transform(numerical_data)

In [13]:
imputer_categorical = SimpleImputer(strategy='most_frequent')
categorical_data = x[:, 1].astype(object)

In [15]:
categorical_data = categorical_data.reshape(-1,1)

In [16]:
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [17]:
print(x)

[['nan' 'Monday' '10']
 ['7' 'Tuesday' 'nan']
 ['5' 'Wednesday' '15']]


In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [23]:
print(x)

[['0.0' '0.0' '1.0' 'Monday' '10']
 ['0.0' '1.0' '0.0' 'Tuesday' 'nan']
 ['1.0' '0.0' '0.0' 'Wednesday' '15']]


In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
print(y)

[2 1 1 ... 1 1 1]


In [28]:
x = ct.fit_transform(x)

In [30]:
print("Shape of x:", x.shape)
print("Shape of y:", y.shape)

Shape of x: (3, 6)
Shape of y: (128913,)


In [48]:
if x.shape[0] == y.shape[0]:
  x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=1)
else:
    print("Jumlah sampel x dan y tidak konsisten.")
    print("Shape of x:", x.shape)
    print("Shape of y:", y.shape)

Jumlah sampel x dan y tidak konsisten.
Shape of x: (3, 6)
Shape of y: (128913,)


In [42]:
if x.shape[0] == y.shape[0]:
  x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=1)
  print(x_train) # Print x_train inside the if block
else:
    print("Jumlah sampel x dan y tidak konsisten.")
    print("Shape of x:", x.shape) # Print the shape of x for debugging
    print("Shape of y:", y.shape) # Print the shape of y for debugging

Jumlah sampel x dan y tidak konsisten.
Shape of x: (3, 6)
Shape of y: (128913,)


In [46]:
from sklearn.model_selection import train_test_split

In [51]:
import numpy as np
from sklearn.model_selection import train_test_split

In [52]:
x = np.random.rand(100, 5)
y = np.random.randint(0, 2, size=100)

In [53]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=1)

In [54]:
print(x_train)

[[3.61904337e-03 3.99323176e-01 7.22691433e-01 6.25659420e-02
  4.89955260e-01]
 [8.77338234e-01 6.92537283e-01 1.26682229e-01 9.20857593e-01
  9.97796651e-01]
 [2.87842033e-01 6.53028729e-01 4.81193805e-02 1.63950932e-01
  2.43631985e-02]
 [3.93374708e-01 4.49264699e-01 6.11653039e-01 3.58667568e-01
  7.51106842e-01]
 [4.11208620e-02 2.73556063e-01 7.02486806e-01 3.08056005e-01
  3.74461421e-01]
 [4.08511854e-01 1.53543591e-01 2.49890342e-01 7.20992174e-01
  7.06056570e-01]
 [1.74522226e-01 4.76851613e-01 7.02525802e-01 7.19085713e-01
  5.76510593e-01]
 [3.74347805e-03 4.04088927e-01 6.18873077e-01 4.44212792e-01
  9.94380296e-01]
 [2.94340717e-01 4.14717919e-01 1.49110702e-01 9.70624410e-01
  7.51739290e-01]
 [3.80309504e-01 9.66876920e-01 6.84190391e-01 3.49941777e-01
  6.31350104e-01]
 [5.47608804e-01 6.57817409e-01 7.30708316e-01 4.35132962e-01
  9.92105986e-01]
 [1.49516488e-01 8.13884805e-01 4.83450804e-01 7.84466147e-01
  6.57092438e-01]
 [1.06163727e-01 3.34706899e-01 4.781419

In [55]:
print(y_train)

[0 0 0 0 1 0 0 0 1 0 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0
 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0
 0 1 0 1 0 0 1 0 0 1 0 1 0 1 1 1]


In [56]:
print(x_test)

[[0.66642816 0.49265362 0.0290799  0.48097938 0.90100491]
 [0.34355356 0.66713543 0.63985359 0.21589184 0.82775106]
 [0.09654307 0.69850802 0.09299951 0.17409481 0.25251998]
 [0.93549821 0.74696734 0.06711646 0.55803332 0.12475496]
 [0.68743691 0.39655408 0.12618479 0.10914523 0.92582562]
 [0.33120117 0.2292787  0.9413556  0.00527866 0.95200548]
 [0.18232333 0.78990792 0.97894775 0.35341289 0.19873646]
 [0.28785861 0.39811102 0.26869826 0.41829966 0.37050042]
 [0.87795014 0.85982163 0.97020171 0.54325002 0.71701035]
 [0.45180858 0.43007964 0.44589975 0.14115845 0.72935131]]


In [57]:
print(y_test)

[1 1 0 0 0 1 1 0 1 0]


In [58]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [59]:
print(x_train)

[[ 3.61904337e-03  3.99323176e-01  7.22691433e-01 -1.37831602e+00
  -2.50756472e-01]
 [ 8.77338234e-01  6.92537283e-01  1.26682229e-01  1.40474445e+00
   1.69949025e+00]
 [ 2.87842033e-01  6.53028729e-01  4.81193805e-02 -1.04956930e+00
  -2.03875447e+00]
 [ 3.93374708e-01  4.49264699e-01  6.11653039e-01 -4.18189316e-01
   7.52135424e-01]
 [ 4.11208620e-02  2.73556063e-01  7.02486806e-01 -5.82300244e-01
  -6.94283694e-01]
 [ 4.08511854e-01  1.53543591e-01  2.49890342e-01  7.56669238e-01
   5.79130337e-01]
 [ 1.74522226e-01  4.76851613e-01  7.02525802e-01  7.50487428e-01
   8.16391478e-02]
 [ 3.74347805e-03  4.04088927e-01  6.18873077e-01 -1.40803964e-01
   1.68637053e+00]
 [ 2.94340717e-01  4.14717919e-01  1.49110702e-01  1.56611625e+00
   7.54564194e-01]
 [ 3.80309504e-01  9.66876920e-01  6.84190391e-01 -4.46483200e-01
   2.92237531e-01]
 [ 5.47608804e-01  6.57817409e-01  7.30708316e-01 -1.70245839e-01
   1.67763657e+00]
 [ 1.49516488e-01  8.13884805e-01  4.83450804e-01  9.62487279e-01

In [60]:
print(x_test)

[[ 0.66642816  0.49265362  0.0290799  -0.02158618  1.32778407]
 [ 0.34355356  0.66713543  0.63985359 -0.88114789  1.04646971]
 [ 0.09654307  0.69850802  0.09299951 -1.0166772  -1.16257143]
 [ 0.93549821  0.74696734  0.06711646  0.2282657  -1.65322325]
 [ 0.68743691  0.39655408  0.12618479 -1.22727999  1.42310226]
 [ 0.33120117  0.2292787   0.9413556  -1.56407337  1.52363991]
 [ 0.18232333  0.78990792  0.97894775 -0.43522791 -1.36911452]
 [ 0.28785861  0.39811102  0.26869826 -0.22482881 -0.709495  ]
 [ 0.87795014  0.85982163  0.97020171  0.18033     0.62119579]
 [ 0.45180858  0.43007964  0.44589975 -1.12347525  0.66858835]]


In [ ]:
print(y_)